/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface XmlViewerComponent {
    'xml': string;
  }
  interface XmlViewerComponentAttributes extends StencilHTMLAttributes {
    'xml'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'XmlViewerComponent': Components.XmlViewerComponent;
  }

  interface StencilIntrinsicElements {
    'xml-viewer-component': Components.XmlViewerComponentAttributes;
  }


  interface HTMLXmlViewerComponentElement extends Components.XmlViewerComponent, HTMLStencilElement {}
  var HTMLXmlViewerComponentElement: {
    prototype: HTMLXmlViewerComponentElement;
    new (): HTMLXmlViewerComponentElement;
  };

  interface HTMLElementTagNameMap {
    'xml-viewer-component': HTMLXmlViewerComponentElement
  }

  interface ElementTagNameMap {
    'xml-viewer-component': HTMLXmlViewerComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
